<?php

// This file is part of the Moodle block "EJSApp File Browser"
//
// EJSApp File Browser is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// EJSApp File Browser is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// The GNU General Public License is available on <http://www.gnu.org/licenses/>
//
// EJSApp File Browser has been developed by:
//  - Luis de la Torre: ldelatorre@dia.uned.es
//	- Ruben Heradio: rheradio@issi.uned.es
//
//  at the Computer Science and Automatic Control, Spanish Open University
//  (UNED), Madrid, Spain

/** 
 * Post-process 'a href' links and draw proper icons for xml state files created
 * by ejsapp. 
 * 
 * @package    block
 * @subpackage ejsapp_file_browser
 * @copyright  2012 Luis de la Torre and Ruben Heradio
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later  
 */

/**
* Processes 'a href' links and draws proper icons for xml state files created
* by ejsapp.
* @return string The html code with the links and images of the xml files
* 
* @param content_text
*/
function process_state_files($content_text) {
  global $DB, $USER, $CFG; 
  preg_match_all('/<\s*a\s+href\s*=\s*"([^"]*)">/i', $content_text, $all_xml_matches);
  foreach ($all_xml_matches[1] as $match) { //For each .xml file
    if (preg_match('/\/.+[.]xml/i', $match, $state_file_match)) {
      $slices = preg_split('/\//', $state_file_match[0]);
      $state_file = urldecode($slices[sizeof($slices) - 1]);
      //get $ejsapp_id
      $file_record = $DB->get_record('files', array('filename' => $state_file, 'component' => 'mod_ejsapp', 'filearea' => 'private', 'userid' => ($USER->id)));
      if (!$file_record) {
  	    $source = array();
      } else {
  	     preg_match('/ejsappid=(\d+)/', $file_record->source, $source);
      }
      if (!empty($source)) { //Replace link only if the file was generated by ejsapp. New link uses ejsappid to reference the appropiate EJSApp instance
        $ejsapp_id = $source[1];
        $ejsapp_record = $DB->get_record('ejsapp', array('id' => $ejsapp_id));
        if ($ejsapp_record) {
          $new_code = $CFG->wwwroot . "/mod/ejsapp/view.php?n=" . $ejsapp_id . "&state_file=" . $file_record->contextid . "/" 
          . $file_record->component . "/" . $file_record->filearea . "/" . $file_record->itemid . "/" . $file_record->filename;
          $reg = preg_quote($match, '/');
  
          $content_text = preg_replace('/' . $reg . '/', $new_code, $content_text);
          // replace icon
          preg_match("/(<img.+$state_file.+src=[\"|']).+([\"|'].+>)/Ui", $content_text, $image_match);
  
          $content_text = preg_replace("/(<img.+$state_file.+src=[\"|']).+([\"|'].+>)/Ui",
          $image_match[1] .
          $CFG->wwwroot . '/blocks/ejsapp_file_browser/pix/ejsapp_icon.gif' . 
          $image_match[2],
          $content_text);
        }
      }
    }
  } // foreach ()
  return $content_text;
}

?>
